REGION_CAPTION_SINGLE_REGION_FREE_FORMAT_CATEGORY_NAME_STAGE2 = [
    "What is the category name of [OBJ]? Answer the question with its category name in free format.",
    "What is the category name of [OBJ]? Answer with its category name.",
    "Identify the category of [OBJ].",
    "What would you call [OBJ]? Provide its category name.",
    "Give the category name for [OBJ].",
    "Classify [OBJ] and provide its category name.",
    "What is the category of [OBJ]?",
    "What is [OBJ]'s category name?",
    "Describe [OBJ] with its category name.",
    "What is the most fitting category name for [OBJ]?",
    "Provide the category name for [OBJ].",
    "Classify [OBJ] and name its category.",
    "What is the category name for [OBJ]?",
    "What is the proper name for [OBJ]?",
    "Give the category for [OBJ].",
    "What would you categorize [OBJ] as?",
    "Name [OBJ] based on its category.",
    "What is the category name for [OBJ]?",
    "Give a category name for [OBJ].",
    "Provide the category name for [OBJ].",
    "What is the category of [OBJ]?",
]

REGION_CAPTION_SINGLE_REGION_SHORT_PHRASE_STAGE2 = [
    "Can you provide me with a short phrase to describe [OBJ]? Answer the question with a short phrase.",
    "Give a short phrase that describes [OBJ].",
    "What short phrase can describe [OBJ]?",
    "Provide a short phrase for [OBJ].",
    "What is a short phrase that best represents [OBJ]?",
    "Describe [OBJ] using only a short phrase.",
    "Can you summarize [OBJ] with a short phrase?",
    "What is the best short phrase for [OBJ]?",
    "Offer a short phrase for [OBJ].",
    "What short phrase would you use for [OBJ]?",
    "Give a concise short phrase for [OBJ].",
    "What short phrase summarizes [OBJ]?",
    "Provide a suitable short phrase for [OBJ].",
    "What is a fitting short phrase for [OBJ]?",
    "What’s an appropriate short phrase for [OBJ]?",
    "Give a quick short phrase to describe [OBJ].",
    "Can you suggest a short phrase for [OBJ]?",
    "What short phrase would you assign to [OBJ]?",
    "Provide a quick short phrase for [OBJ].",
    "What short phrase explains [OBJ]?",
]


REGION_CAPTION_SINGLE_REGION_BREIFLY_STAGE2 = [
    "Can you provide me with a brief description of [OBJ]? Answer the question with brief description.",
    "Give a brief description of [OBJ].",
    "What brief description can you provide for [OBJ]?",
    "Provide a brief description for [OBJ].",
    "What is a brief description of [OBJ]?",
    "Describe [OBJ] in a few sentences.",
    "Can you summarize [OBJ] with a brief description?",
    "What is the best brief description for [OBJ]?",
    "Offer a brief description for [OBJ].",
    "How would you describe [OBJ] briefly?",
    "What brief summary can describe [OBJ]?",
    "Provide a suitable brief description for [OBJ].",
    "What is a fitting brief description for [OBJ]?",
    "What’s an appropriate brief description for [OBJ]?",
    "Can you suggest a brief description for [OBJ]?",
    "What brief description would you assign to [OBJ]?",
    "What brief description explains [OBJ]?",
]

REGION_CAPTION_ONE_SENTENCE_STAGE2 = [
    "Can you provide a one sentence description of [OBJ] in the image? Answer the question with a one sentence description.",
    "Describe [OBJ] in one sentence.",
    "What is a one sentence description of [OBJ]?",
    "Provide a one sentence description for [OBJ].",
    "Summarize [OBJ] in one sentence.",
    "How would you describe [OBJ] in a single sentence?",
    "Give a one sentence summary of [OBJ].",
    "Describe [OBJ] using only one sentence.",
    "What is the best one sentence description for [OBJ]?",
    "Offer a one sentence description for [OBJ].",
    "What is a fitting one sentence to describe [OBJ]?",
    "What’s an appropriate one sentence description for [OBJ]?",
    "Can you suggest a one sentence description for [OBJ]?",
    "Provide a one sentence explanation for [OBJ].",
    "What single sentence would describe [OBJ]?",
    "Give a concise one sentence description of [OBJ].",
    "What single sentence explains [OBJ]?",
    "How would you summarize [OBJ] in one sentence?",
]

COUNTING_SINGLE_REGION_STAGE2 = [
    "How many [OBJ] are there in this image? Answer the question with the number of objects and locate them with object indexes.",
    "Can you count how many [OBJ] are present in the image? Provide the total count along with the corresponding object indexes.",
    "Identify and count all the [OBJ] in this image. Please return the number of objects and their respective indexes.",
    "How many instances of [OBJ] do you see in this image? Report the count and the indexes of each detected object.",
    "Locate all [OBJ] in this image and count them. Provide the number along with their object indexes.",
    "Please count the [OBJ] present in the image and provide their total number along with the index of each object.",
    "Count the number of [OBJ] visible in the image and give the total along with the index of each object.",
    "Determine how many [OBJ] are in this image and list their indexes along with the total count.",
    "Find and count all [OBJ] in the image. Provide the object indexes along with the total number.",
    "How many [OBJ] can you find in this image? Return the count and their respective object indexes.",
]

GROUNDING_SINGLE_REGION_STAGE2 = [
    "Please detect [OBJ] in this image. Answer the question with object indexes.",
    "Detect [OBJ] with object indexes.",
    "Find [OBJ] in the image and provide the object indexes.",
    "Detect [OBJ] in the image and return the object indexes.",
    "What are the object indexes for [OBJ] in this image?",
    "Locate [OBJ] in the image and give the object indexes.",
    "Identify [OBJ] in the image and provide the corresponding indexes.",
    "Detect and return the indexes of [OBJ] in this image.",
    "Please locate [OBJ] and answer with its object indexes.",
    "Find the object indexes for [OBJ] in this image.",
    "Can you detect [OBJ] in the image? Provide the object indexes.",
    "Provide the object indexes for [OBJ] detected in this image.",
    "What are the indexes for [OBJ] detected in the image?",
    "Find [OBJ] in this image and answer with its indexes.",
    "Can you locate [OBJ] and provide the object indexes?",
    "Detect [OBJ] and return the object indexes in this image.",
    "Identify and give the object indexes for [OBJ] in the image.",
    "Please find [OBJ] in the image and return the indexes.",
    "Where is [OBJ] in this image? Provide the object indexes.",
    "Can you locate [OBJ] in this image and give the indexes?",
    "Please detect [OBJ] and provide the object indexes.",
]

BREIF_CAPTION_WITH_GROUDING_STAGE2 = [
    "Please breifly describe this image in one sentence and detect all the mentioned objects. Answer the question with grounded answer.",
    "Please briefly describe this image and detect all the mentioned objects. Answer with grounded object indexes.",
    "Breifly describe this image with grounded answer",
    "Provide a brief description of this image and detect the objects mentioned in the description.",
    "Describe this image briefly and ground all the mentioned objects by providing their indexes.",
    "Give a concise description of the image and detect all the objects mentioned in the description.",
    "What is a brief description of the image? Provide the object indexes for all mentioned objects.",
    "Summarize this image briefly and ground the mentioned objects with their indexes.",
    "Describe this image and detect all the mentioned objects, returning their indexes.",
    "Provide a short description of the image and ground the objects that are mentioned.",
    "What is a quick description of this image? Detect the objects mentioned and provide their indexes.",
    "Give a brief description and detect all mentioned objects, grounding them with their object indexes.",
    "Can you briefly describe this image and also detect the mentioned objects? Provide grounded object indexes.",
    "What is a simple description of the image? Detect and provide indexes for the mentioned objects.",
    "Provide a short description and ground the objects mentioned in the image.",
    "Give a quick description of the image and provide the indexes of all mentioned objects.",
    "Summarize this image and ground all the objects mentioned by providing their indexes.",
    "Describe this image and detect all the mentioned objects. Provide grounded object indexes as the answer.",
    "What is a brief description of this image? Detect the objects in the description and provide their indexes.",
    "Offer a short summary of the image and ground all the mentioned objects by providing their object indexes.",
    "Provide a short caption of the image and detect all mentioned objects with their indexes.",
    "Give a concise summary of the image and detect all mentioned objects, returning their object indexes.",
]

DETAILED_CAPTION_WITH_GROUDING_STAGE2 = [
    "Please provide a detailed description of the image and detect all the mentioned objects. Answer the question with grounded object indexes.",
    "Give a thorough description of the image and detect all mentioned objects, providing their object indexes.",
    "Describe the image in detail and ground all the mentioned objects by returning their object indexes.",
    "What is a detailed description of the image? Detect and provide the indexes for the mentioned objects.",
    "Provide a detailed explanation of this image and ground all the mentioned objects.",
    "Can you describe the image in detail and detect the objects mentioned, returning their indexes?",
    "Describe all the key details in the image and detect the mentioned objects with their indexes.",
    "Provide a complete and detailed description of the image and ground the mentioned objects.",
    "Give a comprehensive description of the image and provide the object indexes for all mentioned objects.",
    "What is happening in this image? Provide a detailed description and detect the mentioned objects with their indexes.",
    "Describe the content of this image in detail and ground the objects mentioned.",
    "Offer a full description of the image and provide the object indexes for all detected objects.",
    "What is a detailed narrative of the scene in this image? Detect and provide indexes for the mentioned objects.",
    "Explain the image thoroughly and provide the object indexes for all mentioned objects.",
    "Provide a detailed description of the image and ground the mentioned objects with their indexes.",
    "Give a detailed overview of the image and detect all mentioned objects by returning their indexes.",
    "Can you explain the details of the image and ground the mentioned objects, providing object indexes?",
    "Provide a detailed narrative of this image and detect the objects mentioned, returning their indexes.",
    "What is a full description of the image? Ground the mentioned objects and provide their indexes.",
    "Describe all the important details in the image and ground the objects mentioned with their indexes.",
    "Describe this image in detail with grounded answer.",
]
